FROM alpine:latest

COPY usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
COPY zipepub /usr/local/bin/zipepub

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
    apk update && apk upgrade && \
    apk --no-cache add ca-certificates zip && \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    chown root /usr/local/bin/zipepub &&\
    chmod u+x /usr/local/bin/zipepub

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8
