FROM alpine:latest

COPY usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
    apk update && apk upgrade && \
    apk --no-cache add ca-certificates libxslt docbook-xsl && \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8
ENV XML_CATALOG_FILES /etc/xml/catalog
